name: Push to Main or Release

on:
  push:
    branches:
      - main
      - "release/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered by push to main or release branch"
