name: Deploy App

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: docker build -t ${{ github.event.inputs.service }} .
      - name: push
        run: docker push ${{ github.event.inputs.service }}
