name: Deploy App

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: "staging"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run for production
        if: ${{ github.event.inputs.environment == 'prod' }}
        run: echo "Deploying to PRODUCTION!"

      - name: Run for staging
        if: ${{ github.event.inputs.environment == 'staging' }}
        run: echo "Deploying to STAGING"
