name: CI

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Make a choice
        options:
          - prod
          - stage
          - dev
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: |
          echo "choice is ${{ github.event.inputs.choice }}" / ${{ inputs.choice }}
