name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - test
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "Deploying..."
