name: Deploy App

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: "staging"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "Deploying to PRODUCTION!"
